### ISSUE TITLE
Read user data (name, email) from .npmrc

### ISSUE THREAD

**Issue by sapegin** [sapegin/mrm#11]
~~Most likely it should be a method(s) in mrm-core.~~

**Comment by sapegin** [comment]
Useful `.npmrc` [options](https://docs.npmjs.com/misc/config):

* `init-author-name`
* `init-author-email`
* `init-author-url`
* `init-license`

**Comment by sapegin** [comment]
Set config:

```
npm set init-author-name="Your Name"
```

Read config:

```js
const rc = require('rc');
const config = rc('npm');
console.log(config['init-author-name']);
```

**Comment by sapegin** [comment]
We can also read some data from Git config:

```
require('git-user-name')() // User name
require('git-user-email')() // Email
require('git-username')() // GitHub user name
```

**Comment by andywer** [comment]
> require('git-user-name')() // User name
> require('git-user-email')() // Email
> require('git-username')() // GitHub user name

I like single-responsibility packages, but this is almost absurd 😅

**Comment by kof** [comment]
It is only absurd if your tools don't allow to separate them easily.

**Comment by sapegin** [comment]
https://github.com/sapegin/user-meta

**Comment by sapegin** [comment]
It may look something like that but I’m not sure about the API:

```
const meta = require('user-meta');
function task(config) {
	const { name, email, url, licenseFile } = config
		.defaults({ licenseFile: 'License.md' })
		.defaults(meta)
		.require('name', 'email', 'url')
		.values();
```

**Comment by sapegin** [comment]
Take a look at the PR: https://github.com/sapegin/mrm/pull/14 🍕
