### ISSUE TITLE
Add option to set yaml spec version 

### ISSUE THREAD

**Issue by aleung** [sapegin/mrm#112]
In mrm-core the `yaml` API by default reads and writes yaml file in 1.2 spec. However, sometime we need the file in yaml 1.1 spec. A specific example is that `yes` is string in yaml 1.2 but docker-compose still consider it a boolean as in yaml 1.1.

It could be solved by adding an option in `yaml` API to specify the yaml spec version. The underlay [yaml](https://eemeli.org/yaml/#options) dependency already provide the `version` option. 

I had tried to update mrm-core, but I found difficult that the `yaml` API doesn't reserve an `option` argument and there is already an optional argument `defaultValue`. If I append an `options` to the argument list, then `defaultValue` must be provided in order to set `options`.

``` js
yaml(filename, defaultValues)                 // current

yaml(filename, defaultValues, options)        // `defaultVaules` becomes mandatory to set `options`

yaml(filename, {defaultValues, yamlVersion})  // make `defaultValues` a property of the `options`
                                              // it breaks API compatibility
```

**Comment by sapegin** [comment]
I'm for the second example: this makes the change non-breaking and keeps the default values consistent with other functions, like `json`.
