### ISSUE TITLE
Load tasks from npm

### ISSUE THREAD

**Issue by sapegin** [sapegin/mrm#12]
One possible way to do that is by a name convention like `mrm-task-pizza`. Mrm will try to load a `pizza` task locally as it does now and if it’s not found will try to `require('mrm-task-pizza')`.

We should also make it work with scoped packages.

**Comment by sapegin** [comment]
![image 2017-08-24 at 2 18 23 pm](https://user-images.githubusercontent.com/70067/29666092-35c71dc4-88d7-11e7-8500-c768ed9fc678.png)

**Comment by andywer** [comment]
Cool. Alternative would be `https://npmjs.com/package/X` instead of `npm install -g X`, but not sure which one's better

**Comment by sapegin** [comment]
Not sure too. I was also thinking about “X npm package installed globally” — global installation is an important detail.

@kof @okonet @bebraw What do you guys think?

**Comment by sapegin** [comment]
We have the first task on npm: https://github.com/sapegin/mrm-tasks/tree/master/packages/mrm-task-gitter 🍕
