### ISSUE TITLE
Package lock updates

### ISSUE THREAD

**Issue by brettz9** [sapegin/mrm#127]
With npm 7 now available, running install gives a very different set of package-lock's. If possible, it'd be nice to be submit a PR which cleans up that noise if you're ok using npm 7.

Or, even more ideal from my perspective if you're ok with it, switching to pnpm to save on disk space. But if not, it'd be nice to be able to commit the package-lock updates.

**Comment by sapegin** [comment]
Feel free to update the files to npm 7.

I don't think forcing contributors to use pnpm is worth the effort.
