### ISSUE TITLE
Cannot add lint-staged: only eslint, stylelint, prettier or custom rules are supported.

### ISSUE THREAD

**Issue by mikemfleming** [sapegin/mrm#147]
### Expected
`npx mrm lint-staged` runs without error.

### Actual 
```
$ nvm use 14.15.5
Now using node v14.15.5 (npm v6.14.11)
$ npx mrm lint-staged
npx: installed 240 in 8.473s
Running lint-staged...

Cannot add lint-staged: only eslint, stylelint, prettier or custom rules are supported.
```

**Comment by sapegin** [comment]
The error message is clear I think: that's what the task supports now.

**Comment by foxyblocks** [comment]
I get this same error when running the example from the [mrm documentation](https://mrm.js.org/docs/mrm-task-lint-staged#usage)

```
npm install -g mrm mrm-task-lint-staged
mrm lint-staged
```

If this usage isn't supported how should the lint-staged task be used?

**Comment by vogelino** [comment]
I also get this message and I disagree with you @sapegin. This error message doesn't help me, as I don't know what to do from there. I do use eslint and prettier, so a message that tells me that only eslint and prettier is supported sounds contradictory to me. Any suggestion on how to fix this issue? @mikemfleming @foxyblocks could you solve your problem?
