### ISSUE TITLE
Tests for tasks

### ISSUE THREAD

**Issue by okonet** [sapegin/mrm#15]
I would like to contribute to tasks but without tests it is very fragile ATM. Do you think there is an easy way to add tests for them.

My concern is that since tasks are basically a set of side-effects it is tricky to write tests for them. If the task modifies a file, it is rather simple to add snapshot tests for those but this will still require to mock the real implementation or introduce a way to work with temp files.

Ideally, I think, it would be great to get test utilities for each "transformation" / "task" but I can imagine this is a big effort.

PS: This is more a conversation starter.

**Comment by sapegin** [comment]
Yeah, I really want to test tasks but I don’t know an easy way to do that yet. In mrm-core I sue [memfs](https://github.com/simonc/memfs) to avoid creating and reading real files. So probably we could make some kind of file system snapshots based on that.

We could read / write a folder into / from an object like this:

```js
{
  '.gitignore': 'foo\nbar',
  '.eslintrc': '…',
};
```

So the workflow would like this:

1. Manually create a snapshot with initial state.
2. Run a function to write a snapshot to a file system.
3. Run an Mrm task.
4. Run a function to read a new snapshot.
5. Pass a new snapshot to Jest’s `toMatchSnapshot()`.

**Comment by sapegin** [comment]
And probably we should read files as JSON/array if possible instead of just strings — that would make snapshot diffs more readable.

**Comment by okonet** [comment]
> Manually create a snapshot with initial state.

I think we could just add a snapshot serializer that would take care of all those steps. See https://facebook.github.io/jest/docs/configuration.html#snapshotserializers-array-string

Here is an example of the serializer: https://github.com/rayrutjes/jest-serializer-html

**Comment by sapegin** [comment]
We need to create the initial file structure before running a test, so that won’t be enough.

**Comment by okonet** [comment]
Oh you mean the `__fixtures__` directory? Yeah, that we should do manually.

**Comment by sapegin** [comment]
If we’re going to use real files to store the initial state.

**Comment by sapegin** [comment]
Looks like memfs already has everything we need:

```js
import {fs, vol} from 'memfs';

const json = {
    './README.md': '1',
    './src/index.js': '2',
    './node_modules/debug/index.js': '3',
};
vol.importJSON(json, '/app');

fs.readFileSync('/app/README.md', 'utf8'); // 1
vol.readFileSync('/app/src/index.js', 'utf8'): // 2

vol.writeFileSync('/foo', 'bar');
expect(vol.toJSON()).to.eql({"/foo": "bar"});
```

**Comment by sapegin** [comment]
I’m experimenting with memfs and after bunch of issues and pull requests test case look really nice:

```js
jest.mock('fs');

const { vol } = require('memfs');
const { copyFiles } = require('../fs');

afterEach(vol.reset.bind(vol));

describe('copyFiles()', () => {
	it('should copy a file', () => {
		vol.fromJSON({ 'tmpl/a': 'pizza' });

		copyFiles('tmpl', 'a');

		expect(vol.toJSON()).toMatchSnapshot();
	});

	it.skip('should copy multiple files', () => {
		vol.fromJSON({ 'tmpl/a': 'pizza', 'tmpl/b': 'coffee' });

		copyFiles('tmpl', ['a', 'b']);

		expect(vol.toJSON()).toMatchSnapshot();
	});

	it.skip('should pass options to cpFile', () => {
		const json = { 'tmpl/a': 'pizza', a: 'pizza' };
		vol.fromJSON(json);

		copyFiles('tmpl', 'a', { overwrite: false });

		expect(vol.toJSON()).toEqual(json);
	});
});
```

As soon as https://github.com/streamich/memfs/pull/30 is merged.

**Comment by sapegin** [comment]
I’ve moved all the default tasks to a separate repo and have added tests: https://github.com/sapegin/mrm-tasks
