### ISSUE TITLE
Error in new 3.0 version

### ISSUE THREAD

**Issue by mehunk** [sapegin/mrm#159]
I'm a new user for this mrm tool.

When I used this tool as the tutorial said, I always saw the error message below and no config file was created successfuly.

> $ mrm
> $ mrm editorconfig
> $ mrm gitignore
>
> Preset “default” not found.
> 
> We’ve tried to load “mrm-preset-default” and “default” npm packages.

But when I downgraded the version to 2.6.2, the tool became to be normal. So I think there may be some bugs in the new 3.0 version.

**Comment by acyuta** [comment]
Same situation.

**Comment by lewisloofis** [comment]
Is it because `mrm-preset-default` deprecated? I'm unable to run this via `npx` either

<img width="1280" alt="Screen Shot 2021-04-14 at 21 24 36" src="https://user-images.githubusercontent.com/15197755/114726838-e9860980-9d67-11eb-917b-331cb8bcc718.png">

**Comment by scarow** [comment]
I am also getting this error.

```
$ npx mrm lint-staged

npx: installed 298 in 15.018s

Preset “default” not found.

We’ve tried to load “mrm-preset-default” and “default” npm packages.
```

**Comment by luankefei** [comment]
+1

**Comment by JarryChung** [comment]
+1

**Comment by mehunk** [comment]
First of all, installing the mrm-preset-default package will solve the problem.

**Comment by hailun3202475** [comment]
Same situation.too

**Comment by dotcore** [comment]
> First of all, installing the mrm-preset-default package will solve the problem.

First of all, that doesn't work with npx. I tested this on a freshly installed system, this does not work with 3.0.0 or 3.0.1

I used `npx mrm@2.6.2 lint-staged` as a workaround, which actually works.

**Comment by riywo** [comment]
This worked for me:

```
$ npx -p mrm mrm
Need to install the following packages:
  mrm
Ok to proceed? (y)
Usage

    mrm                                                # List of available tasks
    mrm <task>                                         # Run a task or an alias
    mrm <task> --dir ~/unicorn                         # Custom config and tasks folder
    mrm <task> --preset unicorn                        # Load config and tasks from a preset
    mrm <task> --config:foo coffee --config:bar pizza  # Override config options
```

**Comment by renmm** [comment]
I use the latest version of MRM and also encounter this problem. No matter which task I follow, I will report an error:

```shell
npx mrm umi3
```
![image](https://user-images.githubusercontent.com/2681624/176711506-27ff5c42-9a4a-41a8-bfad-45977bc943ec.png)

```shell
npx mrm gitignore license
```
![image](https://user-images.githubusercontent.com/2681624/176711894-e88733d0-0d26-40bf-b8a4-bee9a38312b3.png)

why? nrm@4.0.0  is that the same problem ?
