### ISSUE TITLE
New line being removed

### ISSUE THREAD

**Issue by okonet** [sapegin/mrm#19]
When running tasks I noticed that often they also remove the new line `/n` at the end which is required by my `.editorconfig`.

![2017-09-05 at 10 04](https://user-images.githubusercontent.com/11071/30051286-b72989da-9221-11e7-92c8-a1863a0ded8d.png)

**Comment by sapegin** [comment]
That would be hard to fix I’m afraid. Any ideas what to do? Should we read `.editorconfig` and respect it? That would be super cool ;-)

**Comment by sapegin** [comment]
I think we can extend `json` to respect `.editorconfig` on save. We can use [editorconfig-core-js](https://github.com/editorconfig/editorconfig-core-js) for that I think.

**Comment by okonet** [comment]
I was thinking of not modifying the whole file unless needed. But your solution might work as well.

**Comment by sapegin** [comment]
This would be way to complex and would require a whole rewrite ;-)

I think it’s OK (and even good) if Mrm will reformat the whole file according to EditorConfig rules.

**Comment by okonet** [comment]
Yeah, probably you're right.

One related issue I had was that mrm has completely reformatted my `.gitignore` file as well. I wouldn't expect that TBH.

**Comment by sapegin** [comment]
Could you show me the diff?

**Comment by okonet** [comment]
https://github.com/okonet/lint-staged/pull/256/files#diff-a084b794bc0759e7a6b77810e01874f2

**Comment by sapegin** [comment]
Yeah, that wasn’t a good idea to remove empty lines ;-? Could you open a separate issue for that? I’m not sure what would be the best approach here.

**Comment by okonet** [comment]
Done: https://github.com/sapegin/mrm/issues/20

**Comment by sapegin** [comment]
This may be usefult: [eclint](https://github.com/jedmao/eclint).

**Comment by sapegin** [comment]
Nope, it has absolutely crazy API no docs how to use it:

https://github.com/jedmao/eclint/blob/941b176c65aa1affc1b4a6a48cf95c3181021488/lib/eclint.spec.ts#L19-L35

**Comment by sapegin** [comment]
PR is here: https://github.com/sapegin/mrm-core/pull/9 ;-)

**Comment by sapegin** [comment]
Done in [mrm-core 2.4.0](https://github.com/sapegin/mrm-core/releases/tag/v2.4.0).
