### ISSUE TITLE
Don't create .gitignore for husky

### ISSUE THREAD

**Issue by H4M5TER** [sapegin/mrm#192]
I tried using mrm to initialize lint-stage and I found that it created `.husky/.gitignore` which is not necessary.

Doing `husky install` will create `.husky/_` folder which already ignored by Git.
`.husky/_/.gitignore` tells git to ignore every files including itself in the folder so I don't even feel it before mrm created another `.gitignore`.

I think just calling `husky install` would be nice.

**Comment by millette** [comment]
Also of interest:

> .husky/.gitignore is now unnecessary and can be removed.

Since [husky v7.0.0](https://github.com/typicode/husky/releases/tag/v7.0.0)
