### ISSUE TITLE
Do not remove empty lines in lines().save()

### ISSUE THREAD

**Issue by okonet** [sapegin/mrm#20]
When adding new lines, there is no need to modify user-generated content.

See https://github.com/okonet/lint-staged/pull/256/files#diff-a084b794bc0759e7a6b77810e01874f2 as an example of unwanted new lines removal.

**Comment by sapegin** [comment]
Probably just checking a trailing new line (and keeping it) when adding new items would be enough.

**Comment by sapegin** [comment]
> user-generated content

By the way there’s no such distinction in Mrm and most likely will never be.

**Comment by okonet** [comment]
Let's put it that way: "the content that existed before the mrm was applied"

**Comment by sapegin** [comment]
It’s the same ;-)
