### ISSUE TITLE
.js files

### ISSUE THREAD

**Issue by streamich** [sapegin/mrm#21]
Just wanted to see what you think about `.js` files, say I want to install Webpack, it comes with `webpack.config.js`.

Will you parse the JS files and modify their AST, with `esprima` and such?

**Comment by sapegin** [comment]
That’s a tough question ;-) I think working with AST directly would be too complicated, probably it’s better to use [jscodeshift](https://github.com/facebook/jscodeshift) — their API seems more readable and better suite the task.

**Comment by sapegin** [comment]
Closing this for now. Feel free to open a new issue of send a PR if you see how can we improve Mrm.
