### ISSUE TITLE
Accept package versions in install

### ISSUE THREAD

**Issue by sapegin** [sapegin/mrm#23]
Something like this:

```js
install({
  jest: '^21.0.0'
})
```

It should accept a version range and should only update `package.json` if the current range doesn’t satisfy a new one.

**Comment by codejockie** [comment]
I've never contributed to open source projects before, would like to contribute to this. Any fresher's guide?

**Comment by sapegin** [comment]
@codejockie that’s awesome! I highly recommend [this course](http://makeapullrequest.com/) to get started with GitHub workflow.

The actual work should be done in the [mrm-core](https://github.com/sapegin/mrm-core) repo. We have the [install](https://github.com/sapegin/mrm-core#install-and-uninstall-npm-packages) method that accepts a list of npm package names. But if the package is already installed in a project it would just skip it. We want to have an ability to specify a required version for each package. 

You’ll need to use something like [semver.satisfies](https://github.com/npm/node-semver) to check if the currently installed version satisfies the requirement. To find out the currently installed package version I’d try something like this:

https://github.com/bahmutov/deps-ok/blob/add1e64e1659b2fca4f71c09f551ff833c513dc6/src/utils.js#L61-L69

Does it make sense? Do you have more questions?

**Comment by codejockie** [comment]
I'd check it out and let you know if I have more questions.
Thank you.
