### ISSUE TITLE
Run all tasks in a preset

### ISSUE THREAD

**Issue by aleung** [sapegin/mrm#24]
I'm trying to use mrm to standardize all projects in my product line. All our file templates and configuration can be set by creating our own preset. That's fine.

But developer has to list all tasks to be executed. How about adding a command to run all tasks in a preset?

**Comment by sapegin** [comment]
Create an alias that runs all tasks.

**Comment by aleung** [comment]
Thanks. I managed to make it work:

Create a task with name `all` in my preset:

```
.
├── all
│   └── index.js
├── task1
│   └── index.js
├── task2
│   └── index.js
├── config.json
└── package.json
```

In the task `all`, iterate all other tasks and run them:

``` index.js
const { resolve, join } = require('path');
const { readdirSync, lstatSync } = require('fs');

function task() {
    const root = resolve(__dirname, '../');
    readdirSync(root)
        .filter(path => path !== 'all' && path !== 'node_modules')
        .filter(path => lstatSync(join(root, path)).isDirectory())
        .forEach(task => {
            require(`../${task}`)();
        });
}

task.description = 'Run all tasks in this preset';
module.exports = task;
```

Run below command will execute all tasks in my preset:
`mrm all --preset=mypreset`

**Comment by sapegin** [comment]
Yeah, that’s one way. An alias would be easier ;-)

**Comment by aleung** [comment]
You're right. Alias is easier. I didn't notice that config of alias can be put inside preset as well.
