### ISSUE TITLE
What exactly is this for?

### ISSUE THREAD

**Issue by trusktr** [sapegin/mrm#27]
I read the README, but I'm not sure what I'd actually use mrm for.

It is similar to [Builder](https://github.com/FormidableLabs/builder/)? Or more like [Projector](https://github.com/projectorjs/projector-cli) or [Gulp](https://github.com/gulpjs/gulp) for just running tasks?

How does mrm relate to multiple repos or multiple projects?

In particular, I'm looking to make a monorepo that has packages that I publish to NPM, where these packages are unrelated and they'd have their own version numbers not in sync (unlike Lerna's default locked mode that keeps versions in sync), and I'd like to share the same build steps with all the projects so that I don't have to manage confugration for each project/package. Something like Lerna would let me run the same command in all repos, but it doesn't dictate anything about how each project or package will be built or if they even share any configuration. Builder let's us run the same sort of build steps in any repo or project that prescribes to the "archetype" which means I could, f.e., share a webpack build configuration with all projects and build them all in the same way.

How/where does mrm fit into having a monorepo where we want to take advantage of the same build tools and configurations for all projects/packages, and easily update and publish some or all of these packages?

**Comment by sapegin** [comment]
You can configure Lerna to publish independent versions, so I guess it's the best for your use case. 

Mrm is closer to Yeoman generators but with better updates and tools to work with common config file formats. It's an alternative to monorepos: it helps you to keep configuration of multiple projects in sync but allow per-project customizations.

These two links may better explain what it is and whether it’s good for your use case:

* http://blog.sapegin.me/all/mrm
* https://www.youtube.com/watch?v=5tHfAf4bRcM&t=1s

**Comment by bebraw** [comment]
Maybe it's time to close this and condense the answer to the readme somehow?
