### ISSUE TITLE
Allowing async tasks

### ISSUE THREAD

**Issue by thetutlage** [sapegin/mrm#29]
Currently all tasks has to be synchronous and hence using modules like https://github.com/SBoudrias/Inquirer.js is impossible.

I am happy to work on adding the `async` tasks, but wanted to know if you are interested in same?

If yes, I will share the docs around async API and then start working on the PR.

**Comment by sapegin** [comment]
That would be super awesome I think! Thank you for interest! 🦄

**Comment by thetutlage** [comment]
@sapegin Thanks for replying quickly 😄 . MRM is a fantastic tool and I am using it to the fullest to keep my growing projects in sync. https://github.com/adonisjs/mrm-preset

**Here's the proposal**

## Introducing async tasks

The async tasks enables a whole lot more operations than just the file operations provided by `mrm-core`. For example: An [init](https://github.com/adonisjs/mrm-preset/blob/develop/init/index.js) task, which ask for some questions upfront and creates a config file.

## Syntax
The tasks can be marked as `async` in 3 ways. 

1. Using the `async` keyword.
2. Returning a promise.
3. Using `done` style callbacks (I don't personally like them, so feel free to share your opinions).

## Async keyword

```js
async function task (config, argv) {
  await someAsyncOperation()
}
```

## Returning promise

```js
function task (config, argv) {
  return someAsyncOperation()
  	.then()
}
```

## Done style callback
The `done` style callback accepts `error` as the first parameter. If error exists, it will be thrown when executing the task.

```js
function task (config, argv, done) {
  someAsyncOperation()
  	.then(() => {
  	  done()
  	})
  	.catch((error) => {
  	  done(error)
  	})
}
```

## Dis-allow overloading
A task can only return `Promise` or make use of `done` callback. Both are not allowed together. It is more of a design limitation than a technical limitation, mixing Promises and callbacks is not a good idea.

## Executing multiple tasks
Since `mrm` allows `aliases` to an array of tasks, we will make modifications in https://github.com/sapegin/mrm/blob/master/src/index.js#L54 to run a sequential loop.

**Comment by sapegin** [comment]
Thanks! I think just 1 and 2 would be more than enough, no need to support callbacks and add extra complexity.
