### ISSUE TITLE
npm install might fail if one of the dependencies don't satisfy engines range

### ISSUE THREAD

**Issue by okonet** [sapegin/mrm#36]
I just had an issue when the `mrm lint-staged` failed during `yarn add` phase since one of the deep dependencies had `engines` defined and it didn't satisfy lint-staged range.

I could install dependencies manually with `yarn add XXX --ignore-engine` and now wondering if this should be the default behavior. WYT?

**Comment by sapegin** [comment]
Hm, isn't the `engines` field here for a reason? So it's not supposed to work if you don't have the right version.

**Comment by okonet** [comment]
I guess so. Probably you’re right and we shouldn’t assume anything.
