### ISSUE TITLE
No module resolution for overridden tasks

### ISSUE THREAD

**Issue by saibotsivad** [sapegin/mrm#4]
I created a file `~/dotfiles/mrm/config.json` and used the template provided in the Readme.

Then I made a folder `~/dotfiles/mrm/license` and copied [both these files](https://github.com/sapegin/mrm/tree/master/src/tasks/license) into that folder.

Then I ran the command `mrm` and received the error: `Error: Cannot find module 'mrm-core'`

How are the dependencies in `~/dotfiles/mrm/*` expected to be resolved? I could make `~/dotfiles/mrm/package.json` and then `npm install --save` my dependencies, but were you expecting a different approach?

This should probably get put in the `Readme` file.

**Comment by sapegin** [comment]
Yeah, you need a `package.json` in that folder. Will be happy to merge a PR with docs improvements ;-)

**Comment by saibotsivad** [comment]
Maybe like this? https://github.com/sapegin/mrm/pull/5

**Comment by sapegin** [comment]
Merged, thanks!
