### ISSUE TITLE
What does MRM stand for?

### ISSUE THREAD

**Issue by jiqbal48** [sapegin/mrm#50]
knowing this will help me remember it : )

**Comment by jiqbal48** [comment]
so i am watching ur conference video about MRM https://www.youtube.com/watch?v=5tHfAf4bRcM and you explained it in the beginning... but it was still hard to catch the audio of what was said 🤕 
i think it would be helpful to have a text explanation on the readme. 

Btw, really enjoying ur video; this tool seems amazing.

**Comment by sapegin** [comment]
I think it was in the readme originally but I've removed it.

It stands for "marmot" but actually I've tried to find a short name that's easy to type and still available on npm ;-)

**Comment by ismay** [comment]
Maybe @rauchg will give you use of his cfg name on npm (https://www.npmjs.com/package/cfg)? That is, if you like the name and he doesn't mind transferring it. It seems very applicable to me.

**Comment by sapegin** [comment]
@ismay Why does it matter?

**Comment by ismay** [comment]
> @ismay Why does it matter?

Ah, did I misunderstand you? I though you were still looking. Disregard my comment then :).
