### ISSUE TITLE
About embracing the command line for interactive configuration

### ISSUE THREAD

**Issue by lucasconstantino** [sapegin/mrm#51]
I've being using this project for little time, and I think it's configuration pattern is really amazing for most cases. Being able to define global wise config setups that you often use is very handy. But, the current command line way of providing/overriding configs is, in my perspective, very annoying. Either with configuration files or command line parameters, someone that's using `mrm` for the first time for, say, configuring husky will _need_ to read trough the related task to be able to determine if the outcome is what he expects, and only then execute `npx mrm lint-staged` with the proper config inline or set in some configuration file.

My point is I think this whole project is not far from being able to benefit from proper interactive command line to allow the user, with a single command and with no previous reading of documentations, to configure specifics to each task with a single action.

This could definitely be opt-in, as for the current expectation of things. This could even benefit from defaults (based on config files or command line) to make the process faster and simpler for those more advanced users.

So, my initial idea for that would be something similar to that:

```
$ npx mrm -i lint-staged
```

Due to the interactive mode set to on, this script would then ask interactive for the each option defined in the `lint-staged` task, fulfilling defaults by respecting global config files (or even command line parameters). We could use a prompting CLI tool such as [enquirer](https://github.com/enquirer/enquirer) for that, and we could benefit from enquirer prompt types as a pattern for each task module to define it's configs as well, giving proper capabilities to each task to define how each of their configs might be configurable (text input, multiple choice, list, etc).

I'm already up to do that implementation using a simple `mrm` task as an example. We could and should _definitely_ be retro-compatible in the outcome, and as far as I looked into tasks code so far, there is currently no way we could infer config types so that we would only need changing the core packages - that means there would be some slight changes to be done in each task, but those tasks that don't implement it should work the same, but with no interactive configuration.

Any thoughts?

**Comment by sapegin** [comment]
Hey, I think it's an awesome idea! I also think we can make it fist-run default for each task and show default values as defaults for each query, and then ask "don't show again for this task" in the end and save user's choice to their local config file. This will improve discoverability of default options and make configuring Mrm much easier. What do you think?

**Comment by lucasconstantino** [comment]
Totally agree.

I think it's interesting to consider the types of users this package is useful to, though. I, particularly, discovered it when setting up `lint-staged` - they mention `mrm` as the easiest way of install, and it's outstanding that, in combination with `npx`, I don't need to pollute _anything_ to get `lint-staged` setup in my project - not my machine, not the project itself. I personally think this is a huge goal for this project's acceptance, as it could become a go-to solution for many tools out there as their "easiest path" of install.

Taking that in mind, I definitely agree with your proposal, but I also think your proposal is most usually beneficial for people that _often_ scaffold new projects - be it an open-source, be it commercial - and I tend to believe this might not be the majority of people benefiting this kind of solution, though I might be wrong. You are one of those people, I can see that, and I'm definitely also, so for me this "don't show again for this task" is very, very desirable, but I would consider other things so to avoid disturbing those who are one-time-users of this tool.

**Comment by sapegin** [comment]
I guess we can start with opt-in interactive mode and then think how to improve it ;-)

**Comment by lucasconstantino** [comment]
Discussion has evolved into #53 implementation and #55 follow up on task refactors.
