### ISSUE TITLE
No template for the "undefined" found, skipping

### ISSUE THREAD

**Issue by okonet** [sapegin/mrm#7]
I've followed the installation instructions and added following config to `~/.mrm/config.json`

```json
{
    "name": "Andrey Okonetchnikov",
    "email": "andrey@okonet.ru",
    "url": "http://okonet.ru",
    "github": "okonet",
    "indent": "2",
    "readme": "README",
    "license": "LICENSE",
    "aliases": { 
        "node": ["license", "readme", "package", "editorconfig", "eslint", "gitignore"]
    }
}
```

but then I run a command I see

```
➜ mrm license                                      
Running license...
No template for the "undefined" found, skipping
```

**Comment by okonet** [comment]
This seems to be the problem: https://github.com/sapegin/mrm/blob/master/src/tasks/license/index.js#L11

**Comment by sapegin** [comment]
What’s in your `package.json`?

**Comment by okonet** [comment]
See https://github.com/sapegin/mrm/issues/7#issuecomment-313458222

**Comment by sapegin** [comment]
Ah, that explains ;-) Should be easy to fix. Do we need an option for a default license?

**Comment by okonet** [comment]
I'd say MIT by default or provide a way to pass it as argument?

**Comment by sapegin** [comment]
All three would work. Do you want to fix that? ;-)

**Comment by okonet** [comment]
I could take a look.

**Comment by sapegin** [comment]
Awesome! 🍕
