### ISSUE TITLE
Support scoped presets and tasks

### ISSUE THREAD

**Issue by filipekiss** [sapegin/mrm#75]
I came across mrm by chance and I love the idea of having "programmable configurations". Great job!

I've been trying to build a preset to share with my team, but we're using Github Registry so all the packages must be scoped. 

It would be great if mrm could support scoped packages like `@myorg/mrm-preset-default` by just calling `mrm license --preset @myorg/default`. The same would work for tasks, so `mrm @myorg/custom-task` would look for `@myorg/mrm-task-custom-task`.

Yarn supports this, for example `yarn create @myorg/package` will look for `@myorg/create-package`.

I'm willing to give it a go with a pull-request if that's something you're interested in.

Thanks again for the great tool!

**Comment by sapegin** [comment]
Sounds like a good feature, feel free to send a pull request! 👾
