### ISSUE TITLE
npm readme has bad link

### ISSUE THREAD

**Issue by scott-joe** [sapegin/mrm#78]
https://www.npmjs.com/package/mrm has a link to 
>Command line tool to help you keep configuration (package.json, .gitignore, .eslintrc, etc.) of your open source projects in sync.
> 
> See [../Readme.md](https://github.com/sapegin/mrm/blob/HEAD/documentation).

and that doesn't work. It should probably just go to https://github.com/sapegin/mrm/tree/master/docs or something.

Cheers.

**Comment by sapegin** [comment]
Fixed ;-)
