### ISSUE TITLE
Automatic version appending during install breaks github dependencies.

### ISSUE THREAD

**Issue by betaorbust** [sapegin/mrm#89]
Issue
------
Passing a github or other supported services ((npm)[], (yarn)[]) through Mrm's `install` causes the installer to throw an error. This appears to be because the service-based installs do not support versioning, and we append a `@${version}` to every attempted install.  
https://github.com/sapegin/mrm/blob/48fe50f0ef7dfd685f5f830ed46546385802eefe/packages/mrm-core/src/npm.js#L134-L137

Proposed solutions
----
1. **Seamless but hard:** Detect and non-registry installs to mirror NPM/Yarn's capabilities.
2. **Expands API, but easy:** Add an escape hatch (perhaps passing `null` as the version in an explicit version config, to signal leaving off the `@${version}` during the install call?

**Comment by sapegin** [comment]
I'd prefer the first one ;-)

How hard is hard? Should we do anything other than checking whether the name could be an npm package name with something like [validate-npm-package-name](https://github.com/npm/validate-npm-package-name)?

**Comment by betaorbust** [comment]
I prefer the first as well.
`validate-npm-package-name` looks like it would cover it, but I'm just not fully versed in the intricacies of what does and doesn't count as a registry package. Looking through the yarn implementation of the resource resolvers was pretty wild. https://github.com/yarnpkg/yarn/tree/eb2b565bb9b948e87b11119482ebc184a9d66141/src/resolvers/exotics

`validate-npm-package-name` is already in the package-lock, so no change in install size to add it.
